# See start.sh for documentation on interfacing the cFS app for code hot reloading
# See tools/cFS-GroundSystem/cmd.sh for documentation on sending packets to the cFS applications
# NOTE: cFS must be running using docker-compose up (this will start the ground station too)

version: '3'

services:
  cfs:
    build:
        context: ./
        dockerfile: ./Dockerfile
        args:
          - ENABLE_UNIT_TESTS=false
          - SIMULATION=native
          - BUILDTYPE=debug
          - OMIT_DEPRECATED=true
    stdin_open: true
    tty: true
    volumes:
      - ./:/cFS/source
    cap_add: 
      - CAP_SYS_RESOURCE
    networks:
      - default
  gnd:
    build:
        context: ./tools/cFS-GroundSystem
        dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - cfs
    networks:
      - default

  
networks:
  default:
    internal: true    