version: '3'

services:
  cfs:
    build:
        context: ./
        dockerfile: ./Dockerfile
        args:
          - ENABLE_UNIT_TESTS=false
          - SIMULATION=native
          - BUILDTYPE=debug
          - OMIT_DEPRECATED=true
    cap_add: 
      - CAP_SYS_RESOURCE
    networks:
      - default
  
networks:
  default:
    internal: true    