version: '3.1'

services:
    rpi4:
        container_name: rpi4
        restart: "no"
        environment:
            O: build-rpi4
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            BUILD: cpu2
        build:
            context: ./dockerfiles
            dockerfile: rpi4.Dockerfile
        volumes:
          - ./:/cfs
    dev:
        container_name: dev
        restart: "no"
        networks:
            - sat-link
        environment:
            O: build-dev
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            SIMULATION: native
            BUILD: cpu1
        ports:
        - '1235:1235'
        cap_add: 
            - CAP_SYS_RESOURCE
        build:
            context: ./dockerfiles
            dockerfile: ubuntu.Dockerfile
        volumes:
          - ./:/cfs
    gnd:
        container_name: gnd
        build:
            context: ./ground-station
            dockerfile: Dockerfile
        restart: "no"
        networks:
            - sat-link
        environment:
        - EXTERNAL_PORT=5000
        ports:
        - '5000:3000'
        - '5001:5001'
        volumes:
        - ./ground-station:/home/node/app
        - /home/node/app/node_modules

networks:
    sat-link:
        driver: bridge
