version: '3.1'

services:
    rpi4:
        container_name: rpi4
        restart: "no"
        environment:
            O: build-rpi4
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            BUILD: cpu2
        build:
            context: ./dockerfiles
            dockerfile: rpi4.Dockerfile
        volumes:
          - ./:/cfs
    dev:
        container_name: dev
        restart: "no"
        networks:
            - sat-link
        environment:
            O: build-dev
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            SIMULATION: native
            BUILD: cpu1
        ports:
        - '1235:1235'
        cap_add: 
            - CAP_SYS_RESOURCE
        build:
            context: ./dockerfiles
            dockerfile: ubuntu.Dockerfile
        volumes:
          - ./:/cfs
    yamcs:
        build:
            context: ./dockerfiles
            dockerfile: yamcs.Dockerfile
        hostname: yamcs
        container_name: yamcs
        env_file: .env
        command: "/run_yamcs.sh"
        volumes:
            - ./yamcs:/yamcs
            - ./dockerfiles/run_yamcs.sh:/run_yamcs.sh
        networks:
            - sat-link
        ports:
            - "8090:8090"
            - "10015:10015/udp"
            - "${TO_PORT}:${TO_PORT}/udp"
            - "${CI_PORT}:${CI_PORT}"

networks:
    sat-link:
        driver: bridge
