# See start.sh for documentation on interfacing the cFS app for code hot reloading
version: '3'

services:
  cfs:
    build:
        context: ./
        dockerfile: ./Dockerfile
        args:
          - ENABLE_UNIT_TESTS=false
          - SIMULATION=native
          - BUILDTYPE=debug
          - OMIT_DEPRECATED=true
    stdin_open: true
    tty: true
    volumes:
      - ./:/cFS/source
    cap_add: 
      - CAP_SYS_RESOURCE
    networks:
      - default
  
networks:
  default:
    internal: true    