version: '3.1'

services:
    rpi4:
        container_name: rpi4
        restart: "no"
        environment:
            O: build-rpi4
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            BUILD: cpu2
        build:
            context: ./dockerfiles
            dockerfile: rpi4.Dockerfile
        volumes:
          - ./:/cfs
    dev:
        container_name: dev
        restart: "no"
        environment:
            O: build-dev
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true"
            SIMULATION: native
            BUILD: cpu1
        cap_add: 
            - CAP_SYS_RESOURCE
        build:
            context: ./dockerfiles
            dockerfile: ubuntu.Dockerfile
        volumes:
          - ./:/cfs
